### ISSUE TITLE
Cannot see device

### ISSUE THREAD

**Issue by feklee** [hackerspaceshop/BluetoothSerial#1]
In January I obtained a Teensy 3.2 plus Bluetooth LE 4.0 Module from Hackerspaceshop. I soldered them, and when connected to USB the Bluetooth shield’s blue LED blinks. Using the Arduino IDE, I built `setup.ino` for the Teensy and uploaded it to the device. However, `blubber` is not detectable, neither from my PC (Win7 x64, LogiLink [BT0037](http://www.logilink.com/Products_LogiLink/Bluetooth/USB_Adapter/Bluetooth_40-Adapter_USB_20_Micro_BT0037.htm)), neither from my phone ([Fx0](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox_OS/Phone_guide/Fx0)).

_Could this be a hardware issue? Did I do something wrong? How do I find out more?_

The Teensy works fine. We’re using it for our [STM project](https://wiki.fablab.berlin/STM), wired. It would be nice to connect via Bluetooth, though.

**Comment by elliottkember** [comment]
I have the same problem @feklee. Did you ever resolve this?

**Comment by overflo23** [comment]
sorry, i dont  know what causes your problems.
it works for the other customers.
i am afraid i can not help you out :(
